INSERT INTO a_staging.stg_receipt_items
(
    receipt_id,
    user_id,
    item_barcode,
    brand_code,
    competitive_product,
    competitor_rewards_group,
    deleted,
    item_description,
    discounted_item_price,
    final_price,
    item_number,
    item_price,
    metabrite_campaign_id,
    needs_fetch_review,
    needs_fetch_review_reason,
    original_final_price,
    original_metabrite_barcode,
    original_metabrite_description,
    original_metabrite_item_price,
    original_metabrite_quantity_purchased,
    original_receipt_item_text,
    partner_item_id,
    points_earned,
    points_not_awarded_reason,
    points_payer_id,
    prevent_target_gap_points,
    price_after_coupon,
    quantity_purchased,
    rewards_group,
    rewards_product_partner_id,
    target_price,
    user_flagged_barcode,
    user_flagged_description,
    user_flagged_new_item,
    user_flagged_price,
    user_flagged_quantity
)
SELECT 
    receipt_id::TEXT,
    user_id::TEXT,
    item_barcode::TEXT,
    brand_code::TEXT,
    competitive_product::TEXT,
    competitor_rewards_group::TEXT,
    deleted::BOOLEAN,
    item_description::TEXT,
    NULLIF(discounted_item_price, '')::NUMERIC(10,2),
    NULLIF(final_price, '')::NUMERIC(10,2),
    item_number::TEXT,
    NULLIF(item_price, '')::NUMERIC(10,2),
    metabrite_campaign_id::TEXT,
    needs_fetch_review::BOOLEAN,
    needs_fetch_review_reason::TEXT,
    NULLIF(original_final_price, '')::NUMERIC(10,2),
    original_metabrite_barcode::TEXT,
    original_metabrite_description::TEXT,
    NULLIF(original_metabrite_item_price, '')::NUMERIC(10,2),
    NULLIF(original_metabrite_quantity_purchased, '')::INTEGER,
    original_receipt_item_text::TEXT,
    partner_item_id::TEXT,
    NULLIF(points_earned, '')::NUMERIC(10,2),
    points_not_awarded_reason::TEXT,
    points_payer_id::TEXT,
    prevent_target_gap_points::BOOLEAN,
    NULLIF(price_after_coupon, '')::NUMERIC(10,2),
    NULLIF(quantity_purchased, '')::INTEGER,
    rewards_group::TEXT,
    rewards_product_partner_id::TEXT,
    NULLIF(target_price, '')::NUMERIC(10,2),
    user_flagged_barcode::TEXT,
    user_flagged_description::TEXT,
    user_flagged_new_item::BOOLEAN,
    NULLIF(user_flagged_price, '')::NUMERIC(10,2),
    NULLIF(user_flagged_quantity, '')::INTEGER

FROM public.receipt_items
ON CONFLICT (unique_hash) DO NOTHING;
